import random

def fun_lista_de_palavras(tema_escolhido):
    """
    função que armazena todo o banco de palavras do jogo
    """
    if tema_escolhido == "1":
        times_nba = [
            "Atlanta Hawks", 
            "Boston Celtics", 
            "Brooklyn Nets", 
            "Charlotte Hornets", 
            "Chicago Bulls", 
            "Cleveland Cavaliers", 
            "Dallas Mavericks", 
            "Denver Nuggets", 
            "Detroit Pistons", 
            "Golden State Warriors", 
            "Houston Rockets", 
            "Indiana Pacers", 
            "LA Clippers", 
            "Los Angeles Lakers", 
            "Memphis Grizzlies", 
            "Miami Heat", 
            "Milwaukee Bucks", 
            "Minnesota Timberwolves", 
            "New Orleans Pelicans", 
            "New York Knicks", 
            "Oklahoma City Thunder", 
            "Orlando Magic", 
            "Philadelphia 76ers", 
            "Phoenix Suns", 
            "Portland Trail Blazers", 
            "Sacramento Kings", 
            "San Antonio Spurs", 
            "Toronto Raptors", 
            "Utah Jazz", 
            "Washington Wizards"]
        
        return random.choice(times_nba)
    
    elif tema_escolhido == "2":
        times_nfl = ['Arizona Cardinals', 
                     'Atlanta Falcons', 
                     'Baltimore Ravens', 
                     'Buffalo Bills', 
                     'Carolina Panthers', 
                     'Chicago Bears', 
                     'Cincinnati Bengals', 
                     'Cleveland Browns', 
                     'Dallas Cowboys', 
                     'Denver Broncos', 
                     'Detroit Lions', 
                     'Green Bay Packers', 
                     'Houston Texans', 
                     'Indianapolis Colts', 
                     'Jacksonville Jaguars', 
                     'Kansas City Chiefs', 
                     'Las Vegas Raiders', 
                     'Los Angeles Chargers', 
                     'Los Angeles Rams', 
                     'Miami Dolphins', 
                     'Minnesota Vikings', 
                     'New England Patriots', 
                     'New Orleans Saints', 
                     'New York Giants', 
                     'New York Jets', 
                     'Philadelphia Eagles', 
                     'Pittsburgh Steelers', 
                     'San Francisco 49ers', 
                     'Seattle Seahawks', 
                     'Tampa Bay Buccaneers', 
                     'Tennessee Titans', 
                     'Washington Football Team']
        
        return random.choice(times_nfl)
    
    elif tema_escolhido == "3":
        paises_do_mundo = [
    'Afeganistão', 
    'África do Sul', 
    'Albânia', 
    'Alemanha', 
    'Andorra', 
    'Angola', 
    'Antígua e Barbuda', 
    'Arábia Saudita', 
    'Argélia', 
    'Argentina', 
    'Armênia', 
    'Austrália', 
    'Áustria', 
    'Azerbaijão', 
    'Bahamas', 
    'Bahrein', 
    'Bangladesh', 
    'Barbados', 
    'Belarus (Bielorrússia)', 
    'Bélgica', 
    'Belize', 
    'Benin', 
    'Bolívia', 
    'Bósnia e Herzegovina', 
    'Botsuana', 
    'Brasil', 
    'Brunei', 
    'Bulgária', 
    'Burkina Faso', 
    'Burundi', 
    'Butão', 
    'Cabo Verde', 
    'Camarões', 
    'Camboja', 
    'Canadá', 
    'Catar', 
    'Cazaquistão', 
    'Chade', 
    'Chile', 
    'China', 
    'Chipre', 
    'Colômbia', 
    'Comores', 
    'Congo (Brazzaville)', 
    'Congo (Kinshasa)', 
    'Coreia do Norte', 
    'Coreia do Sul', 
    'Costa do Marfim', 
    'Costa Rica', 
    'Croácia', 
    'Cuba', 
    'Dinamarca', 
    'Djibuti', 
    'Dominica', 
    'Egito', 
    'El Salvador', 
    'Emirados Árabes Unidos', 
    'Equador', 
    'Eritreia', 
    'Eslováquia', 
    'Eslovênia', 
    'Espanha', 
    'Estados Unidos', 
    'Estônia', 
    'Etiópia', 
    'Fiji', 
    'Filipinas', 
    'Finlândia', 
    'França', 
    'Gabão', 
    'Gâmbia', 
    'Gana', 
    'Geórgia', 
    'Granada', 
    'Grécia', 
    'Guatemala', 
    'Guiana', 
    'Guiné', 
    'Guiné Equatorial', 
    'Guiné-Bissau', 
    'Haiti', 
    'Holanda', 
    'Honduras', 
    'Hungria', 
    'Iêmen', 
    'Ilhas Marshall', 
    'Ilhas Maurício', 
    'Índia', 
    'Indonésia', 
    'Irã', 
    'Iraque', 
    'Irlanda', 
    'Islândia', 
    'Israel', 
    'Itália', 
    'Jamaica', 
    'Japão', 
    'Jordânia', 
    'Kiribati', 
    'Kuwait', 
    'Laos', 
    'Lesoto', 
    'Letônia', 
    'Líbano', 
    'Libéria', 
    'Líbia', 
    'Liechtenstein', 
    'Lituânia', 
    'Luxemburgo', 
    'Macedônia', 
    'Madagascar', 
    'Malásia', 
    'Malaui', 
    'Maldivas', 
    'Mali', 
    'Malta', 
    'Marrocos', 
    'Mauritânia', 
    'México', 
    'Micronésia', 
    'Moçambique', 
    'Moldova', 
    'Mônaco', 
    'Mongólia', 
    'Montenegro', 
    'Namíbia', 
    'Nauru', 
    'Nepal', 
    'Nicarágua', 
    'Níger', 
    'Nigéria', 
    'Noruega', 
    'Nova Zelândia', 
    'Omã', 
    'Palau', 
    'Panamá', 
    'Papua Nova Guiné', 
    'Paquistão', 
    'Paraguai', 
    'Peru', 
    'Polônia', 
    'Portugal', 
    'Quênia', 
    'Quirguistão', 
    'Reino Unido', 
    'República Centro-Africana', 
    'República Dominicana', 
    'República Tcheca', 
    'Romênia', 
    'Ruanda', 
    'Rússia', 
    'Samoa', 
    'San Marino', 
    'Santa Lúcia', 
    'São Cristóvão e Neves', 
    'São Tomé e Príncipe', 
    'São Vicente e Granadinas', 
    'Seicheles (Seychelles)', 
    'Senegal', 
    'Serra Leoa', 
    'Sérvia', 
    'Singapura', 
    'Síria', 
    'Somália', 
    'Sri Lanka', 
    'Suazilândia', 
    'Sudão', 
    'Sudão do Sul', 
    'Suécia', 
    'Suíça', 
    'Suriname', 
    'Tailândia', 
    'Tajiquistão', 
    'Tanzânia', 
    'Timor-Leste', 
    'Togo', 
    'Tonga', 
    'Trinidad e Tobago', 
    'Tunísia', 
    'Turcomenistão', 
    'Turquia', 
    'Tuvalu', 
    'Ucrânia', 
    'Uganda', 
    'Uruguai', 
    'Uzbequistão', 
    'Vanuatu', 
    'Vaticano', 
    'Venezuela', 
    'Vietnã', 
    'Zâmbia', 
    'Zimbábue']

        return random.choice(paises_do_mundo)
